### PR TITLE
Issue 201

### PR DESCRIPTION
**Pull request by invis87**
add possibility to set network where container will be started

### CODE REVIEW

**Review by thomaseizinger — CHANGES_REQUESTED** [review]
Hi @invis87,

thanks for the contribution!
I am happy to merge this although I might give the library a cleanup in the near future as the current design causes a lot of duplication between all the images.

Before we can merge this, please rebase onto the `dev` branch. You seem to have branched off master and hence have unnecessary commits in your PR history.
In addition, a test would be nice that makes sure this feature is actually working!

**Comment by invis87** [comment]
Hi!
Okey, I will rebase :)
Also, looks like for my integration tests I need to create docker network to be able to access one service from another (it is possible to do this through `host.docker.internal`, but not on all platforms). Is it ok if I add network creation to pub trait Docker?

**Comment by thomaseizinger** [comment]
> Hi!
> Okey, I will rebase :)
> Also, looks like for my integration tests I need to create docker network to be able to access one service from another (it is possible to do this through `host.docker.internal`, but not on all platforms). Is it ok if I add network creation to pub trait Docker?

I'd assume it is our only option if we want to expose the functionality of docker as is. Not sure if we should but maybe we can do something clever if we zoom out a bit:

I would assume you have a usecase where you want to start several containers and they should all be on the same network? What if we make the network a configuration parameter of the client - i.e. `Cli` - and all containers started through that client instance are automatically connected to that network?

**Comment by invis87** [comment]
About my case - in integration test I start several containers and most of them do not care about the others. But one container cares. And there is no way to give him connection path in `testcontainers-rs` except through host machine (by `host.docker.internal`) which does not work on Linux for now.

So docker network is the only way I see.

I think your idea - about `Cli` parameter is good and simple. But what if some one want to create two containers in one network and two in another one? Creating to `docker` instances seems strange. From my point of view method to attach image to network is better, like `postgres.with_network(net: &Network)` but I don't know how to implement `Drop` in that case. Looks like `docker.create_network` and save struct somewhere inside.

**Comment by invis87** [comment]
Also, to have access from one container to another in the same net we need to explicitly set container name. Which is also not possible now :(

**Comment by invis87** [comment]
test added

**Comment by thomaseizinger** [comment]
Hi @invis87 !

https://github.com/testcontainers/testcontainers-rs/pull/206 just merged, are you ok with closing this PR?

**Pull request closed without merging**
