### PR TITLE
Minor fixes and updates

### PR DESCRIPTION
**Pull request by otavio**

### CODE REVIEW

**Comment by D4nte** [comment]
How did you do https://github.com/testcontainers/testcontainers-rs/pull/130/commits/4beb37617ae2114d1f29afd5cd7370a6f53ac5fe and what is the difference from the [git hook](https://github.com/testcontainers/testcontainers-rs/blob/6f761608eb48454ba28591db3ca837b1369f9055/.githooks/pre-commit#L3)?

**Comment by otavio** [comment]
> How did you do [4beb376](https://github.com/testcontainers/testcontainers-rs/commit/4beb37617ae2114d1f29afd5cd7370a6f53ac5fe) and what is the difference from the [git hook](https://github.com/testcontainers/testcontainers-rs/blob/6f761608eb48454ba28591db3ca837b1369f9055/.githooks/pre-commit#L3)?

I ran `cargo fmt --all` from nightly.

**Comment by D4nte** [comment]
> > How did you do [4beb376](https://github.com/testcontainers/testcontainers-rs/commit/4beb37617ae2114d1f29afd5cd7370a6f53ac5fe) and what is the difference from the [git hook](https://github.com/testcontainers/testcontainers-rs/blob/6f761608eb48454ba28591db3ca837b1369f9055/.githooks/pre-commit#L3)?
> 
> I ran `cargo fmt --all` from nightly.

Ok so the commit message is incorrect. You just run a nightly release of `rustfmt` instead of a stable one. `rustfmt` was always run "globally" before.

The actual issue is that we do not specific which version of rustfmt should be used.

**Comment by D4nte** [comment]
> I ran `cargo fmt --all` from nightly.

Please note that `--all` has no effect on this project, see `cargo --help`:
```
--all        Format all packages (only usable in workspaces)
```

There are no workspaces in this project.

The only difference is that you ran nightly `rustfmt` instead of stable.

The actual issue is that we do not specify which version of `rustfmt` should be run to format this project.

**Comment by otavio** [comment]
So what? Should I amend the commit log?

**Comment by D4nte** [comment]
> So what? Should I amend the commit log?

Sorry about the confusion, it was kind of a note to myself that we need to fix something (issue opened: #131). @thomaseizinger has triggered the merging of your PR. Thank you for the contribution~

**Comment by thomaseizinger** [comment]
bors retry

**Pull request merged**
