### PR TITLE
Add OrientDB image

### PR DESCRIPTION
**Pull request by wolf4ood**
Hi, 

this PR add the support for OrientDB. 
I started out from the MongoDB one and added support for custom `env_vars`

### CODE REVIEW

**Review by thomaseizinger — CHANGES_REQUESTED** [review]
Thanks for the contribution!

Do you mind squashing your two commits into a single one?

**Comment by wolf4ood** [comment]
Done :)

**Review by thomaseizinger — APPROVED** [review]
Thank you!

bors r+

**Comment by thomaseizinger** [comment]
bors retry

**Comment by thomaseizinger** [comment]
bors retry

**Pull request merged**
