### PR TITLE
Add volume mapping support

### PR DESCRIPTION
**Pull request by otavio**
Fixes: #61.
Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>

### CODE REVIEW

**Comment by otavio** [comment]
I think it is covered as we test the argument passing:

https://github.com/testcontainers/testcontainers-rs/pull/135/commits/b02025745aea0cf16f14f7e3fd4ebda73a8bdd47#diff-caee46d44eed5d3e600d8b8ad2341a5cR335-R336

**Comment by otavio** [comment]
Do you mind creating a release? We're currently forced to use the Git tree for our tests.

**Comment by thomaseizinger** [comment]
> Do you mind creating a release? We're currently forced to use the Git tree for our tests.

Oh yes, sorry about that!
I'll deal with this soon :)

**Pull request merged**
