### PR TITLE
Support healthcheck customization

### LINKED ISSUE #342: Support healthcheck customization in docker run
Some docker images do not have `HEALTHCHECK`, but they do have commands to verify its health status. Support of healthcheck customization can avoid ad-hoc image.

Given zookeeper(#255) as an example, `./bin/zkServer.sh status` could be used as parameter to `--health-cmd` options in `docker run`.

### PR DESCRIPTION
**Pull request by kezhuw**
Sees #341.
Closes #342.

### CODE REVIEW

**Comment by kezhuw** [comment]
Ping @andrey-yantsen for review.

**Comment by andrey-yantsen** [comment]
@kezhuw why me though? :) I don't have write access to the repo.

**Comment by kezhuw** [comment]
O_O

I found through recent commits. Seems that this repo using bots to merge pr. Sorry for interruption.

Ping @thomaseizinger for review.

**Comment by thomaseizinger** [comment]
Thanks for the PR!

I am not fully sold on adding this feature.

We support the `WaitFor::Healthcheck` command so that images which do have a `HEALTHCHECK` instruction can easily be waited on.
If an image does not support that and you need to add the healthcheck command manually, you might as well not use `WaitFor::Healthcheck` and instead just express directly using other `WaitFor` instructions what needs to happen for the image to be ready. Now, it is debatable whether `WaitFor` can express everything that is necessary. I am open to add other `WaitFor` strategies but I'd like to not add too many ways of doing the same thing.

For now, I think it is out of scope of testcontainers-rs to "extend" a container this way. I'd recommend to either:

- Express the "waiting" condition using existing `WaitFor` possibilities
- Add a HEALTHCHECK instruction to the upstream image you are using
- Fork the upstream image or create a new image that is created `FROM` the parent image and add your own HEALTHCHECK instruction

**Comment by kezhuw** [comment]
I think `HEALTHCHECK` customization in testing code has advantages over other approaches:
* `WaitFor::Xyz`: One purpose of this customization to support command execution to detect readiness. I guess it will be similar to "--health-xyz" options in `docker run` if `WaitFor` support similar functionality in future.
* Build dedicated images. Images are hard coded artifacts. It is much difficult to build/publish images (possible in upstream repos) than customization in testing code. Besides, healthcheck customization enables fine control per project(different projects may have different testing environments) other than per image.

**Comment by thomaseizinger** [comment]
If you truly require custom waiting strategies based on commands, you can use `Container#exec`: https://github.com/testcontainers/testcontainers-rs/blob/8d937a8ee53eb9d86a219578c65c10d4a7564db9/src/core/container.rs#L143-L155

**Comment by kezhuw** [comment]
Then I am reinventing the wheel.
* I need a command to execute. It is `--health-cmd`.
* What if the command fails ? Should I retry ?
   * What is the retry interval ? It is `--health-interval`.
   * How many times should I retry ? It is `--health-retries`.
 * What if the command blocks without responding ? Should I consider it as failure after some timeout ? It is `--health-timeout`.
 * Next will be the journey of `--health-start-period`(moby/moby#26664)

**Pull request closed without merging**
