### PR TITLE
Fix WaitFor::Healthcheck

### PR DESCRIPTION
**Pull request by kezhuw**
* Reclaim zombie docker inspect command process
* Panic on unhealthy

### CODE REVIEW

**Comment by kezhuw** [comment]
Without this fix, it could causes `WaitFor::Healthcheck` blocking indefinitely and fails with `runtime/cgo: pthread_create failed: Resource temporarily unavailable` finally due to zombie `docker inspect` processes.

I did not add test case for this fix as this will introduce extra image pulling. But you could see https://github.com/kezhuw/testcontainers-rs/commits/645a37fd33dcd8f145152e2f35e6dc9c1e8e9766.

**Comment by kezhuw** [comment]
I have added an ignored test case in #343 using healthcheck customization.

**Comment by kezhuw** [comment]
Ping @andrey-yantsen for review.

**Comment by andrey-yantsen** [comment]
@kezhuw, hey :) I'm not sure if `panic` is a good idea because we can't know why the container is `unhealthy` (maybe we have a slow CPU, and the container takes a lot of time to start everything up). IMO a better solution would be to introduce a timeout, i.e. if the status is still not `healthy` after X seconds, it's time to panic.

P.S. And yeah, I still don't have the write access :)

**Comment by kezhuw** [comment]
@andrey-yantsen [`HEALTHCHECK`](https://docs.docker.com/engine/reference/builder/#healthcheck) itself has time control. Together with #343, caller call tweak time options. I guess it is a convention in `testcontainers-rs` to panic when condition unmet.

From code, there is no panic in `STARTING` phase. I quoted docs from docker links.
> When a container has a healthcheck specified, it has a health status in addition to its normal status. This status is initially starting. Whenever a health check passes, it becomes healthy (whatever state it was previously in). After a certain number of consecutive failures, it becomes unhealthy.

**Comment by andrey-yantsen** [comment]
Ah, yes, there's `--start-period`. Thanks!

**Review by thomaseizinger — APPROVED** [review]
Yep that looks good to me!

Thank you :)

bors r+

**Pull request merged**
