### PR TITLE
Password mandatory in postgres image

### LINKED ISSUE #147: Postgres Docker image does not start
The official postgres docker image does not start if the "POSTGRES_PASSWORD" environment variable is not specified; consequently, this command always fails:
```rust
docker.run(images::postgres::Postgres::default());
```

### PR DESCRIPTION
**Pull request by ufoscout**
Fix #147

### CODE REVIEW

**Comment by ufoscout** [comment]
Hi @thomaseizinger, pull the latest postgres image you'll see that it does not start if the password is not provided.
Commits squashed.

**Comment by thomaseizinger** [comment]
> Hi @thomaseizinger, pull the latest postgres image and you'll see that it does not start if the password is not provided.
> Commits squashed.

Oh, seems to be a breaking change in the image then, that is annoying :(
We are in the middle of converting this repository to git-flow, so I changed the base branch of your PR to `dev` now.

I've fixed the travis config in #154, do you mind amending and force-pushing you commit again to retrigger your build?

Thanks :)

**Comment by ufoscout** [comment]
@thomaseizinger done @

**Comment by thomaseizinger** [comment]
Thanks @ufoscout !

**Pull request merged**
