### PR TITLE
Add hostname support

### PR DESCRIPTION
**Pull request by maexn**
Adding the support for the docker `--hostname` option

### CODE REVIEW

**Review by thomaseizinger — COMMENTED** [review]
Thanks! Can you explain why you need this in your test setup?

**Comment by maexn** [comment]
Hi @thomaseizinger 

One of the containers in my test setup requires a preset hostname, localhost cannot be used due to the communication between the containers. 
I think Docker's hostname flag would be a nice and lean solution to this problem.

**Comment by thomaseizinger** [comment]
What if you set the name of the container? Does that work for your usecase?

**Comment by silwol** [comment]
Working on the same team as @maexn I think we should elaborate our use case a little further.

One of the containers we start with `testcontainers-rs` contains an instance of [keycloak](https://keycloak.org). Apparently keycloak inserts its own hostname into the id tokens that it hands out to clients.

We want to be able to either run the composition on containers fully inside our automated tests, or to start the same composition interactively for debugging purposes, accessing them from the host through the web frontend of our software.

Because keycloak encodes the hostname into the id tokens, the hostname must be the same in both scenarios. This can be achieved by the workaround of using e.g. `keycloak.localhost`, which resolves to `127.0.0.1` outside the container, and to the other container's ip when used inside. This is what the change enables us to do, but can not be implemented with current stock `testcontainers-rs`.

If you know a different method that allows us to reach the same goal, we'd be happy to use that instead, but given the fact that this is a standard docker feature, I think supporting it makes sense.

**Comment by silwol** [comment]
> How are you using `testcontainers` for this? This sounds like a usecase for `docker-compose`!

We're actually migrating away from `docker-compose` for this use case.

The idea is to have several scenarios available that can be used for tests. The service can be started in multiple instances which coordinate through RabbitMQ and Redis, and include an OIDC provider. Example scenarios:
- Single instance, with example users **Alice**, **Bob**, **Charlie**, **Dave** and **Erin**
- Multiple instances, randomly generated users and simulated mass usage
- Multiple instances, and during the test we restart RabbitMQ or Redis, and verify that the services recover properly
- etc

The use case for interactively debugging the setup comes in whenever a test fails, and you want to be able to analyze why. Then you can execute that single test and keep the `testcontainers` composition running if a specific environment variable is set, and investigate the situation.

Drawbacks we had with `docker-compose`, which is why we started looking around and found `testcontainers` which we really appreciate for that use case:
- `docker-compose` is much more static, starting multiple scenarios in parallel requires a lot of thought to be put into due to fixed ports
- Scenarios of restarting services to test service robustness are much more difficult to implement
- Integration in test code is a lot more verbose, `testcontainers` allows us to provide abstractions a lot easier

**Comment by thomaseizinger** [comment]
Thank you for sharing that!

I am still not sure if I fully understand your usecase. The idea of testcontainers (and the design of `testcontainers-rs` specifically) is to make integration tests of individual components possible. For example if you have a data-access-layer, you want to test your SQL queries against a real database.

This is the usecase I want to serve well with `testcontainers` and until [another maintainer steps up](https://github.com/testcontainers/testcontainers-rs/issues/347), I am somewhat reluctant to repurpose it into something else (like a replacement for docker swarm or docker compose).

> `docker-compose` is much more static, starting multiple scenarios in parallel requires a lot of thought to be put into due to fixed ports

If everything is running in docker, you don't need to expose any host ports so you don't have conflicts.

> Scenarios of restarting services to test service robustness are much more difficult to implement

I am surprised you say that. I've had very good experiences with using `docker-compose` for exactly that:

- Start services with `docker compose up -d`
- Check connectivity: `docker compose -it exec $some_command`
- Stop one service: `docker compose stop some_service`
- Check connectivity again: `docker compose -it exec $some_command`

**Comment by silwol** [comment]
Thanks for taking the time to write such a detailed answer.

> I am still not sure if I fully understand your usecase. The idea of testcontainers (and the design of `testcontainers-rs` specifically) is to make integration tests of individual components possible. For example if you have a data-access-layer, you want to test your SQL queries against a real database.

Ok, if that's how it is intended to be used, we're probably aiming for something that's beyond this scope. The use case we have in mind is to test the full service in interaction with other components. The service and the other components are started using `testcontainers-rs` inside the each test, then the action is performed (requests are sent and their answers verified) and the expected behavior of the service in this scenario is verified.

> This is the usecase I want to serve well with `testcontainers` and until [another maintainer steps up](https://github.com/testcontainers/testcontainers-rs/issues/347), I am somewhat reluctant to repurpose it into something else (like a replacement for docker swarm or docker compose).

Totally understandable, I recognize this situation just too well.

> > `docker-compose` is much more static, starting multiple scenarios in parallel requires a lot of thought to be put into due to fixed ports
> 
> If everything is running in docker, you don't need to expose any host ports so you don't have conflicts.

Yes, as explained above, the test itself sends requests to the "containered" service, and that runs on the host.

> > Scenarios of restarting services to test service robustness are much more difficult to implement
> 
> I am surprised you say that. I've had very good experiences with using `docker-compose` for exactly that:
> 
>     * Start services with `docker compose up -d`
> 
>     * Check connectivity: `docker compose -it exec $some_command`
> 
>     * Stop one service: `docker compose stop some_service`
> 
>     * Check connectivity again: `docker compose -it exec $some_command`

As explained above, the checks are performed in rust code, while this sequence would fit nicely in shell scripts it would be rather cumbersome to implement in rust, at least requiring some level of abstraction in addition. We need to encapsulate that functionality in any case, and `testcontainers-rs` seemed like a nice fit for that.

> `testcontainers` is never going to be a full purpose docker client. The codebase itself is really small and if I understand you correctly in what you want to achieve, I'd suggest building your own integration test harness instead of extending this one with configuration options. `testcontainers` has a very permissive license so you can take whatever code you need from it :)

Thanks a lot! We'll think about how to proceed here. The integration tests dev branch we currently have is actually running quite nicely with just this - as we perceive - rather small improvement to `testcontainers-rs`. Our code will be published as soon as the dev branch is merged. Sadly our GitLab instance is not open to the public, so dev branches cannot be seen until merged to `main` and [published to OpenCoDE](https://gitlab.opencode.de/opentalk/controller).

Feel free to proceed with this PR as desired, we will consider our options for achieving what we need. `testcontainers-rs` proved quite reliable and promising for the use case otherwise.

**Comment by thomaseizinger** [comment]
> The integration tests dev branch we currently have is actually running quite nicely with just this - as we perceive - rather small improvement to `testcontainers-rs`

I agree that it would be a small addition but we have to draw the line somewhere. docker has lots of config options because it servers many usecases. `testcontainers-rs` does not serve all docker usecases. We already support booting up multiple containers and attaching it to the same network. Docker will default the hostname to the container name so from the perspective of this library, you can actually set the hostname.

> > > Scenarios of restarting services to test service robustness are much more difficult to implement
> > 
> > I am surprised you say that. I've had very good experiences with using `docker-compose` for exactly that:
> > 
> > ```
> > * Start services with `docker compose up -d`
> > 
> > * Check connectivity: `docker compose -it exec $some_command`
> > 
> > * Stop one service: `docker compose stop some_service`
> > 
> > * Check connectivity again: `docker compose -it exec $some_command`
> > ```
>
> As explained above, the checks are performed in rust code, while this sequence would fit nicely in shell scripts it would be rather cumbersome to implement in rust, at least requiring some level of abstraction in addition. We need to encapsulate that functionality in any case, and testcontainers-rs seemed like a nice fit for that.

Even though I've not seen your code, I have a hunch of what it might look like because I've written similar tests using `testcontainers-rs` before and let me tell you, it didn't turn out well.

Good tests survive big refactors because they are testing an interface that remains stable. In my experience, automated tests at a level that involve booting up other services are best done using an interface that is also used by users (either through the UI or via an API). That is what I meant with `docker compose -it exec $some_command`. Even if that is not possible for some reason, it might be a lot easier to write yourself a small integration-test client that provides programmatic access to internal APIs, basically, a layer above what you are currently doing.

**Comment by thomaseizinger** [comment]
In any case, thank you for the contribution and explaining the usecase. Unfortunately, we can't accept feature request.

**Comment by thomaseizinger** [comment]
> basically, a layer above what you are currently doing.

What I've found is that in Rust, the typical test-pyramid does not apply if you use the type system properly. In fact, you probably want a fair few end-to-end tests, no integration tests and lots of unit tests (unit meaning a particular, isolated unit of code which can be almost arbitrarily big).

The "integration" test is essentially done by the type checker because it ensures you are using all variables, exhaustively matching on all enum variants, etc. Thus the data-flow is guaranteed to handle all cases. Corner-cases can be tested using unit-tests. Thus, if your e2e tests pass (which implies a passing build), you are covering a lot of ground already. Don't forget that tests also have a (maintenance) cost. Every test you don't have to write is literally saving you money.

`testcontainers-rs` fills a niche that allows you to unit-test components that depend on external services to make sure those edge-cases are covered too as it is often hard to get coverage on that via e2e tests.

**Comment by silwol** [comment]
> > basically, a layer above what you are currently doing.
> 
> What I've found is that in Rust, the typical test-pyramid does not apply if you use the type system properly. In fact, you probably want a fair few end-to-end tests, no integration tests and lots of unit tests (unit meaning a particular, isolated unit of code which can be almost arbitrarily big).

Yes, that's probably true. We currently have a lot of what we call "unit tests", which cover both traditional isolated units of code, and what you call end-to-end tests here, but we don't distinguish these. That's why we are looking into splitting those up into two separate sections, this is where `testcontainers-rs` came in.

The reason why I call them integration tests is because we have a web frontend as well, so the naming "end-to-end tests" is already occupied in our project by tests covering the frontend as well. And yes, at every single employer I had in the past, there was the discussion about which kinds of tests there are and should be, and how they should be named.

Thanks for concluding this ticket, as remarked above we'll investigate our options and decide based on the outcome which direction we will choose. Way better than just remaining silent. :+1:

**Pull request closed without merging**
