### PR TITLE
Fix clippy lint and kafka test

### PR DESCRIPTION
**Pull request by yottabytt**

### CODE REVIEW

**Comment by thomaseizinger** [comment]
Thanks for trying to tackle this! I have unfortunately no experience with kafka so I don't know what is going on here :(

Tried to run the test locally but it failed with:

```
---- test_produce_and_consume_messages stdout ----
thread 'test_produce_and_consume_messages' panicked at 'called `Result::unwrap()` on an `Err` value: (KafkaError (Message production error: MessageTimedOut (Local: Message timed out)), OwnedMessage { payload: Some([77, 101, 115, 115, 97, 103, 101, 32, 48]), key: Some([75, 101, 121, 32, 48]), topic: "test-topic", timestamp: NotAvailable, partition: -1, offset: -1001, headers: None })', tests/kafka.rs:53:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

**Comment by yottabytt** [comment]
Hmm, that shouldn't happen locally. It doesn't happen for me. As the error says, I guess the service is not reachable. May be some misconfiguration? (A while ago it happened coz of some misconfiguration, which I don't remember) I am on MacOS though. 

Anyways, as you could see from https://github.com/testcontainers/testcontainers-rs/pull/296#issuecomment-912133288 , the test run [3501173678](https://github.com/testcontainers/testcontainers-rs/runs/3501173678) was the one that faced the following error 

> ---- test_produce_and_consume_messages stdout ----
thread 'test_produce_and_consume_messages' panicked at 'called `Result::unwrap()` on an `Err` value: KafkaError (Message consumption error: UnknownTopicOrPartition (Broker: Unknown topic or partition))', tests/kafka.rs:69:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

I don't know how Github Actions work. But it looks the subsequent test run [3501162005](https://github.com/testcontainers/testcontainers-rs/runs/3501162005) for #296 seem to have passed with the following output

> running 1 test
test test_produce_and_consume_messages ... ok
test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 25.00s

The test run [3502000684](https://github.com/testcontainers/testcontainers-rs/runs/3502000684) for this PR (#297) also seem to have got the following output

> running 1 test
test test_produce_and_consume_messages ... ok
test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 27.75s

I did try something to reproduce the behavior locally on my machine. I ran the test `test_produce_and_consume_messages` 75 times each on `dev` branch and `yottabytt:fix-lint-and-potentially-fix-kafka-test` branch. 

I was able to see the same error 4 times on the former and 0 times on the latter. This is just a sample though. The latter might also exhibit it. Hope this helps to justify to an extent.

**Comment by thomaseizinger** [comment]
> I don't know how Github Actions work and how it is configured for this repo. What's the purpose of `staging` branch?

We are using [bors](https://bors.tech/) to avoid semantic conflicts between several PRs. bors uses the staging branch to  test a PR against latest `dev` before it merges it in.

I reran the job, lets see what happens :)

**Comment by thomaseizinger** [comment]
It actually seems like it is the podman test that is hanging! Sorry about that. That one also fails on dev and I have no clue why.

**Comment by thomaseizinger** [comment]
I've pushed a commit that disables the podman test for now and opened https://github.com/testcontainers/testcontainers-rs/issues/299 as a result.

**Pull request merged**
